jobs:

# Set an output variable from a job with a matrix
- job: A
  strategy:
    maxParallel: 2
    matrix: 
#       Integration:
#         environment: integration
      QA:
        environment: qaenv
      Production:
        environment: production
  steps: 
  - bash: echo environment $(environment)
    
 
